### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ailich** [EsriOceans/btm#131] opened 2017-06-17 17:17 UTC
I recently installed BTM and it shows up in the Arc workspace but if I click any of the tools I get an error message that says "failed to open toolbox bmt.pyt" and if I try to close the error message it immediately pops back up effectively crashing Arc. I'm running ArcMap 10.5 on a Surface Book. Does anyone know what the issue might be? 

![btm_error](https://user-images.githubusercontent.com/28163862/27254846-4746342a-535f-11e7-9a8e-381d71fd0b37.png)

**Comment by noahslocum** [comment] 2017-08-08 00:24
Hello @ailich, I apologize for the belated response. Have you been able to resolve the issue you described or are you still unable to use BTM?

**Comment by ailich** [comment] 2017-08-28 18:58
@noahslocum I have not been able to install BTM yet

**Comment by scw** [comment] 2017-09-18 16:12
Hello @ailich,

Sorry for the delay in responding to you. It isn't clear what the problem is with the toolbar, but could you try the following steps to cleanly reinstall?

    1. Delete the existing add-in. Customize > Add-In Manager. Select 'Benthic Terrain Modeler (BTM)'. In the right-hand pane, click 'Delete this Add-In'. Close ArcMap.
    2. Install it again from the [ArcGIS Online site](https://www.arcgis.com/home/item.html?id=b0d0be66fd33440d97e8c83d220e7926#!)

If that doesn't work, the deeper solution is to delete the addin installed manually. This is located in:

    %LOCALAPPDATA%\Esri\Desktop10.5\AssemblyCache\{2dac2ae8-b5f3-4263-9f5d-aaed6b47316b} 

Delete that directory entirely, then try reinstalling. If that still doesn't work, let us know and we can look at what might be going wrong. Note that in any case, you should still be able to use the Python toolbox version of BTM by opening the toolbox in the catalog pane, and interacting with the Geoprocessing tools it provides from there.

Cheers,
Shaun

**Comment by ailich** [comment] 2017-11-01 14:12
I deleted the {2dac2ae8-b5f3-4263-9f5d-aaed6b47316b} file and reinstalled but am still having the same issue. I also tried accessing BTM from the Arc Toolbox, but it didn't show up. Since it wasn't there, I right clicked and selected "Add Toolbox" and then chose the "btm.pyt" file, but the toolbox still doesn't show up.

**Comment by jrbrque** [comment] 2017-11-14 19:56
I'm having similar problems. I run the btm.esriaddin and it tells me installation successful. However, when I go to add the toolbox to Arc Toolbox, the btm.pyt icon has an x through it and nothing happens. In ArcMap, it lets me add BTM to the toolbar, but again, not into ArcToolbox. If I try to use any of the BTM tools from the toolbar, about 20 Error windows popup saying "Failed to open toolbox btm.pyt". BTM does come up in the Add-In Manager in ArcMap, and of note here is that the Digital Signature is marked as Untrusted - it looks like the certificate expired 8/16/2017 so I'm wondering if that might be my issue? I have tried removing BTM via the Add-In Manager, and deleting the folders indicated above and reinstalling, but the result is always the same. Any suggestions?

**Comment by ailich** [comment] 2017-11-15 19:19
Finally was able to resolve the issue. Seems to be an issue with Arc and not BTM. I went to the Arc Map installer and chose the repair option and now BTM opens

**Closed** 2017-11-15 19:20 UTC
